In [9]:
from sklearn.datasets import load_wine
import pandas as pd

In [10]:
wine = load_wine()

In [11]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [12]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [14]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [15]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [16]:
df = pd.DataFrame(wine.data,columns = wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [17]:
df['target'] = wine.target

In [18]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [19]:
df.groupby('target').describe()

alcohol                                                             \
         count       mean       std    min     25%     50%     75%    max   
target                                                                      
0         59.0  13.744746  0.462125  12.85  13.400  13.750  14.100  14.83   
1         71.0  12.278732  0.537964  11.03  11.915  12.290  12.515  13.86   
2         48.0  13.153750  0.530241  12.20  12.805  13.165  13.505  14.34   

       malic_acid            ... od280/od315_of_diluted_wines       proline  \
            count      mean  ...                          75%   max   count   
target                       ...                                              
0            59.0  2.010678  ...                         3.42  4.00    59.0   
1            71.0  1.932676  ...                         3.16  3.69    71.0   
2            48.0  3.333750  ...                         1.82  2.47    48.0   

                                                                       
               mean         std    min    25%     50%     75%     max  
target                                                                 
0       1115.711864  221.520767  680.0  987.5  1095.0  1280.0  1680.0  
1        519.507042  157.211220  278.0  406.5   495.0   625.0   985.0  
2        629.895833  115.097043  415.0  545.0   627.5   695.0   880.0  

[3 rows x 104 columns]

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(['target'],axis='columns'),wine.target,test_size=0.25)

In [43]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [44]:
model.score(X_test,y_test)

0.8888888888888888

In [45]:
from sklearn.naive_bayes import GaussianNB
model_G = GaussianNB()
model_G.fit(X_train,y_train)

GaussianNB()

In [46]:
model_G.score(X_test,y_test)

0.9777777777777777

In [47]:
from sklearn.model_selection import cross_val_score

In [50]:
import numpy as np

In [55]:
np.average(cross_val_score(GaussianNB(),wine.data,wine.target))

0.9663492063492063

In [56]:
np.average(cross_val_score(MultinomialNB(),wine.data,wine.target))

0.843968253968254

In [57]:
cross_val_score(GaussianNB(),df.drop(['target'],axis='columns'),wine.target)

array([0.94444444, 0.97222222, 0.97222222, 0.94285714, 1.        ])

In [58]:
cross_val_score(MultinomialNB(),df.drop(['target'],axis='columns'),wine.target)

array([0.75      , 0.75      , 0.80555556, 0.91428571, 1.        ])