In [28]:
import pandas as pd

In [70]:
data = {
    'town':['monreo twonship','monreo twonship','monreo twonship','monreo twonship','monreo twonship','west windsor','west windsor','west windsor','west windsor','robinsville','robinsville','robinsville','robinsville',],
    'area':[2600,3000,3200,3600,4000,2600,2800,3300,3600,2600,2900,3100,3600],
    'price':[550000,565000,610000,680000,725000,585000,615000,650000,710000,575000,600000,620000,695000]
}
df = pd.DataFrame(data)
df

town  area   price
0   monreo twonship  2600  550000
1   monreo twonship  3000  565000
2   monreo twonship  3200  610000
3   monreo twonship  3600  680000
4   monreo twonship  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [30]:
dummies=pd.get_dummies(df.town)
dummies

monreo twonship  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [31]:
merged = pd.concat([df,dummies],axis='columns')
merged

town  area   price  monreo twonship  robinsville  west windsor
0   monreo twonship  2600  550000                1            0             0
1   monreo twonship  3000  565000                1            0             0
2   monreo twonship  3200  610000                1            0             0
3   monreo twonship  3600  680000                1            0             0
4   monreo twonship  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [32]:
final = merged.drop(['town','west windsor'],axis='columns')
final

area   price  monreo twonship  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [33]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [34]:
X = final.drop('price',axis='columns')
X

area  monreo twonship  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [35]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [36]:
model.fit(X,y)

LinearRegression()

In [37]:
model.predict([[2800,0,1]])

/Users/shahmdmesbahulislam/opt/anaconda3/envs/DS_ML/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [38]:
model.predict([[3400,0,0]])

/Users/shahmdmesbahulislam/opt/anaconda3/envs/DS_ML/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [39]:
model.score(X,y)

0.9573929037221873

In [71]:
df

town  area   price
0   monreo twonship  2600  550000
1   monreo twonship  3000  565000
2   monreo twonship  3200  610000
3   monreo twonship  3600  680000
4   monreo twonship  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [42]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [43]:
X = df[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [44]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [72]:
df["town"].unique()

array(['monreo twonship', 'west windsor', 'robinsville'], dtype=object)

In [74]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [75]:
print(ohe)

OneHotEncoder()


In [76]:
ohe.fit_transform(df[["town"]]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [77]:
feature_array=ohe.fit_transform(df[["town"]]).toarray()

In [78]:
ohe.categories_

[array(['monreo twonship', 'robinsville', 'west windsor'], dtype=object)]

In [79]:
feature_labels=ohe.categories_

In [80]:
np.array(feature_labels).ravel()

array(['monreo twonship', 'robinsville', 'west windsor'], dtype=object)

In [81]:
feature_labels=np.array(feature_labels).ravel()

In [82]:
print(feature_labels)

['monreo twonship' 'robinsville' 'west windsor']


In [84]:
after_ohe=pd.DataFrame(feature_array,columns=feature_labels)
after_ohe

monreo twonship  robinsville  west windsor
0               1.0          0.0           0.0
1               1.0          0.0           0.0
2               1.0          0.0           0.0
3               1.0          0.0           0.0
4               1.0          0.0           0.0
5               0.0          0.0           1.0
6               0.0          0.0           1.0
7               0.0          0.0           1.0
8               0.0          0.0           1.0
9               0.0          1.0           0.0
10              0.0          1.0           0.0
11              0.0          1.0           0.0
12              0.0          1.0           0.0

In [85]:
merged_after_ohe = pd.concat([df,after_ohe],axis='columns')
merged_after_ohe

town  area   price  monreo twonship  robinsville  west windsor
0   monreo twonship  2600  550000              1.0          0.0           0.0
1   monreo twonship  3000  565000              1.0          0.0           0.0
2   monreo twonship  3200  610000              1.0          0.0           0.0
3   monreo twonship  3600  680000              1.0          0.0           0.0
4   monreo twonship  4000  725000              1.0          0.0           0.0
5      west windsor  2600  585000              0.0          0.0           1.0
6      west windsor  2800  615000              0.0          0.0           1.0
7      west windsor  3300  650000              0.0          0.0           1.0
8      west windsor  3600  710000              0.0          0.0           1.0
9       robinsville  2600  575000              0.0          1.0           0.0
10      robinsville  2900  600000              0.0          1.0           0.0
11      robinsville  3100  620000              0.0          1.0           0.0
12      robinsville  3600  695000              0.0          1.0           0.0

In [86]:
final = merged_after_ohe.drop(['town','west windsor'],axis='columns')
final

area   price  monreo twonship  robinsville
0   2600  550000              1.0          0.0
1   3000  565000              1.0          0.0
2   3200  610000              1.0          0.0
3   3600  680000              1.0          0.0
4   4000  725000              1.0          0.0
5   2600  585000              0.0          0.0
6   2800  615000              0.0          0.0
7   3300  650000              0.0          0.0
8   3600  710000              0.0          0.0
9   2600  575000              0.0          1.0
10  2900  600000              0.0          1.0
11  3100  620000              0.0          1.0
12  3600  695000              0.0          1.0

In [88]:
X = final.drop('price',axis='columns')
X = X.values
X

array([[2.6e+03, 1.0e+00, 0.0e+00],
       [3.0e+03, 1.0e+00, 0.0e+00],
       [3.2e+03, 1.0e+00, 0.0e+00],
       [3.6e+03, 1.0e+00, 0.0e+00],
       [4.0e+03, 1.0e+00, 0.0e+00],
       [2.6e+03, 0.0e+00, 0.0e+00],
       [2.8e+03, 0.0e+00, 0.0e+00],
       [3.3e+03, 0.0e+00, 0.0e+00],
       [3.6e+03, 0.0e+00, 0.0e+00],
       [2.6e+03, 0.0e+00, 1.0e+00],
       [2.9e+03, 0.0e+00, 1.0e+00],
       [3.1e+03, 0.0e+00, 1.0e+00],
       [3.6e+03, 0.0e+00, 1.0e+00]])

In [89]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [90]:
model.fit(X,y)

LinearRegression()

In [91]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [92]:
model.predict([[3400,0,0]])

array([681241.66845839])